#!/bin/bash


cwd=${PWD##*/}

pwd
cd src
make clean
cd ../
tar --exclude "*svn*" --exclude "*~" --exclude "*#" -cjvf bondi.tar \
 ../$cwd/BSD-LICENCE \
 ../$cwd/install-sh \
 ../$cwd/run-tests-sh \
 ../$cwd/pc_book \
 ../$cwd/prelude \
 ../$cwd/src \
 ../$cwd/tests \
 ../$cwd/xml \
 ../$cwd/net \
 ../$cwd/lib
