#!/bin/bash

cp cygwindll/cygwin1.dll .
cd src
make clean
cd ../
rm bondi.zip
zip -r bondi.zip \
 README-WIN \
 bondi.exe \
 cygwin1.dll \
 BSD-LICENCE \
 pc_book \
 prelude \
 src \
 net \
 tests \
 xml \
 lib

zip -d bondi.zip "*svn*"
rm cygwin1.dll
cp bondi.zip cygwindist
